import 'dart:typed_data';

import 'package:http/http.dart' as http;

import 'api_provider.dart';

/// A PDF generated by the API, with the file name it suggests for saving.
class ReportDownload {
  ReportDownload(this.bytes, this.fileName);

  final Uint8List bytes;
  final String fileName;
}

/// The three admin PDF reports (generated server-side by `Reports/...`).
class ReportProvider extends ApiProvider {
  ReportProvider() : super('Reports');

  Future<ReportDownload> destinationsByCategory() =>
      _download('DestinationsByCategory', 'destinacije-po-kategorijama');

  /// [from] and [to] are whole days (inclusive); either can be left out.
  Future<ReportDownload> userActivity({DateTime? from, DateTime? to}) =>
      _download('UserActivity', 'aktivnost-korisnika', {
        'from': from == null ? null : _date(from),
        'to': to == null ? null : _date(to),
      });

  Future<ReportDownload> popularDestinations({required int top}) =>
      _download('PopularDestinations', 'najpopularnije-destinacije', {'top': top});

  Future<ReportDownload> _download(
    String report,
    String fallbackName, [
    Map<String, dynamic>? query,
  ]) async {
    final response = await send(
      (headers) => http.get(buildUri('$endpoint/$report', query), headers: headers),
    );
    return ReportDownload(
      response.bodyBytes,
      _fileName(response.headers['content-disposition']) ?? 'travelbay-$fallbackName.pdf',
    );
  }

  static String _date(DateTime value) =>
      '${value.year}-${value.month.toString().padLeft(2, '0')}-${value.day.toString().padLeft(2, '0')}';

  /// Reads `filename=...` from the Content-Disposition header set by the API.
  static String? _fileName(String? contentDisposition) {
    if (contentDisposition == null) {
      return null;
    }
    final match = RegExp(r'filename="?([^";]+)"?').firstMatch(contentDisposition);
    return match?.group(1);
  }
}
