import 'dart:io';

import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import 'package:flutter_form_builder/flutter_form_builder.dart';
import 'package:intl/intl.dart';
import 'package:provider/provider.dart';

import '../../layouts/master_screen.dart';
import '../../providers/report_provider.dart';
import '../../utils/dialogs.dart';

/// The three PDF reports. Each is generated by the API, saved where the admin
/// chooses, and can then be opened (and printed) in the default PDF viewer.
class ReportScreen extends StatelessWidget {
  const ReportScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return MasterScreen(
      section: AdminSection.reports,
      title: 'Izvještaji',
      child: ListView(
        padding: const EdgeInsets.all(24),
        children: [
          Text(
            'Izvještaj se generiše na serveru iz trenutnih podataka. Nakon preuzimanja '
            'odaberite gdje da se sačuva PDF, a zatim ga možete otvoriti i odštampati.',
            style: Theme.of(context).textTheme.bodyMedium,
          ),
          const SizedBox(height: 16),
          _ReportCard(
            icon: Icons.category_outlined,
            title: 'Destinacije po kategorijama',
            description: 'Broj destinacija u svakoj kategoriji, njihov udio, broj odobrenih '
                'recenzija i prosječna ocjena po kategoriji.',
            generate: (_) => context.read<ReportProvider>().destinationsByCategory(),
          ),
          const SizedBox(height: 16),
          _ReportCard(
            icon: Icons.people_outline,
            title: 'Aktivnost korisnika',
            description: 'Za svakog korisnika: broj recenzija (i odobrenih), pregleda '
                'destinacija i planova putovanja. Period je opcionalan; bez njega se '
                'uzima cijela historija.',
            parameters: const _PeriodFields(),
            generate: (values) => context.read<ReportProvider>().userActivity(
                  from: values[_PeriodFields.fromField] as DateTime?,
                  to: values[_PeriodFields.toField] as DateTime?,
                ),
          ),
          const SizedBox(height: 16),
          _ReportCard(
            icon: Icons.trending_up,
            title: 'Najpopularnije destinacije',
            description: 'Destinacije poredane po broju pregleda, zatim po broju odobrenih '
                'recenzija i prosječnoj ocjeni.',
            parameters: const _TopField(),
            generate: (values) => context
                .read<ReportProvider>()
                .popularDestinations(top: values[_TopField.field] as int),
          ),
        ],
      ),
    );
  }
}

class _ReportCard extends StatefulWidget {
  const _ReportCard({
    required this.icon,
    required this.title,
    required this.description,
    required this.generate,
    this.parameters,
  });

  final IconData icon;
  final String title;
  final String description;

  /// Optional form fields; their values are passed to [generate].
  final Widget? parameters;
  final Future<ReportDownload> Function(Map<String, dynamic> values) generate;

  @override
  State<_ReportCard> createState() => _ReportCardState();
}

class _ReportCardState extends State<_ReportCard> {
  final _formKey = GlobalKey<FormBuilderState>();
  bool _isGenerating = false;

  Future<void> _download() async {
    final form = _formKey.currentState!;
    if (!form.saveAndValidate()) {
      return;
    }

    setState(() => _isGenerating = true);
    try {
      final report = await widget.generate(form.value);
      final path = await FilePicker.saveFile(
        dialogTitle: 'Sačuvaj izvještaj',
        fileName: report.fileName,
        type: FileType.custom,
        allowedExtensions: const ['pdf'],
        bytes: report.bytes,
      );
      if (path == null || !mounted) {
        return;
      }

      ScaffoldMessenger.of(context)
        ..hideCurrentSnackBar()
        ..showSnackBar(
          SnackBar(
            content: Text('Izvještaj "${widget.title}" je sačuvan: $path'),
            behavior: SnackBarBehavior.floating,
            width: 640,
            duration: const Duration(seconds: 8),
            action: SnackBarAction(label: 'Otvori', onPressed: () => _open(path)),
          ),
        );
    } on Exception catch (e) {
      if (mounted) {
        await showErrorDialog(context, e);
      }
    } finally {
      if (mounted) {
        setState(() => _isGenerating = false);
      }
    }
  }

  /// Opens the saved PDF in the default Windows viewer, from where it can be printed.
  Future<void> _open(String path) async {
    try {
      await Process.start('explorer.exe', [path]);
    } on ProcessException {
      if (mounted) {
        await showErrorDialog(
          context,
          'PDF je sačuvan, ali ga nije moguće automatski otvoriti. Otvorite ga ručno: $path',
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    return Card(
      child: Padding(
        padding: const EdgeInsets.all(20),
        child: FormBuilder(
          key: _formKey,
          child: Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              CircleAvatar(
                radius: 24,
                backgroundColor: theme.colorScheme.secondaryContainer,
                foregroundColor: theme.colorScheme.onSecondaryContainer,
                child: Icon(widget.icon),
              ),
              const SizedBox(width: 20),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(widget.title, style: theme.textTheme.titleMedium),
                    const SizedBox(height: 4),
                    Text(widget.description, style: theme.textTheme.bodyMedium),
                    if (widget.parameters != null) ...[
                      const SizedBox(height: 16),
                      widget.parameters!,
                    ],
                  ],
                ),
              ),
              const SizedBox(width: 20),
              FilledButton.icon(
                onPressed: _isGenerating ? null : _download,
                icon: _isGenerating
                    ? const SizedBox.square(
                        dimension: 18,
                        child: CircularProgressIndicator(strokeWidth: 2),
                      )
                    : const Icon(Icons.picture_as_pdf_outlined),
                label: Text(_isGenerating ? 'Generišem…' : 'Generiši i preuzmi PDF'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

/// Optional "od / do" dates for the user activity report.
class _PeriodFields extends StatelessWidget {
  const _PeriodFields();

  static const fromField = 'from';
  static const toField = 'to';

  static final _format = DateFormat('dd.MM.yyyy.');

  @override
  Widget build(BuildContext context) {
    final form = FormBuilder.of(context);

    return Wrap(
      spacing: 16,
      runSpacing: 12,
      children: [
        SizedBox(
          width: 220,
          child: FormBuilderDateTimePicker(
            name: fromField,
            inputType: InputType.date,
            format: _format,
            firstDate: DateTime(2000),
            lastDate: DateTime(2100),
            decoration: const InputDecoration(
              labelText: 'Od (opcionalno)',
              suffixIcon: Icon(Icons.calendar_month_outlined),
            ),
          ),
        ),
        SizedBox(
          width: 220,
          child: FormBuilderDateTimePicker(
            name: toField,
            inputType: InputType.date,
            format: _format,
            firstDate: DateTime(2000),
            lastDate: DateTime(2100),
            decoration: const InputDecoration(
              labelText: 'Do (opcionalno)',
              suffixIcon: Icon(Icons.calendar_month_outlined),
            ),
            validator: (to) {
              final from = form?.fields[fromField]?.value as DateTime?;
              if (from != null && to != null && to.isBefore(from)) {
                return 'Datum "do" mora biti isti ili nakon datuma "od".';
              }
              return null;
            },
          ),
        ),
        TextButton.icon(
          onPressed: () => form?.patchValue({fromField: null, toField: null}),
          icon: const Icon(Icons.clear),
          label: const Text('Cijeli period'),
        ),
      ],
    );
  }
}

/// How many destinations the popularity report lists.
class _TopField extends StatelessWidget {
  const _TopField();

  static const field = 'top';
  static const _options = [5, 10, 20, 50];

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: 220,
      child: FormBuilderDropdown<int>(
        name: field,
        initialValue: 10,
        decoration: const InputDecoration(labelText: 'Broj destinacija'),
        items: [
          for (final option in _options)
            DropdownMenuItem(value: option, child: Text('Top $option')),
        ],
      ),
    );
  }
}
